name: ArenaWar
version: 1.0.0
main: com.pvpsurvival.ArenaWarPlugin
api-version: '1.21'
author: BoltAI
description: Arena War - Intensiver PvP-Kampf für Multiplayer-Runden

commands:
  start:
    description: Starte eine neue Arena War Runde
    usage: /start
    permission: arenawar.start
    permission-message: Du hast keine Berechtigung, Spiele zu starten!

permissions:
  arenawar.start:
    description: Erlaubt das Starten von Arena War Runden
    default: op